# This workflow will check code formatting of golang project
name: Check Formatting of Go Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Download Dependencies
      run: go mod tidy
      working-directory: ./backend

    - name: Check Code formatting
      run: |
        if [ $(gofmt -l .) ]; then
        echo "Go files must be formatted. Run 'gofmt -s -w .' to fix."
        gofmt -d .
        exit 1
        fi
      working-directory: ./backend
