# This workflow will test a golang project's unittest
name: Go Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    - name: Download Dependencies
      run: go mod tidy

      working-directory: ./backend
    - name: Build
      run: go build -v ./...
      working-directory: ./backend

    - name: Test
      run: go test -v ./...
      working-directory: ./backend
