# This workflow will lint the Nuxt project using Bun
name: Lint Nuxt Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Install dependencies
        run: bun install
        working-directory: ./frontend

      - name: Run ESLint
        run: bun run lint
        working-directory: ./frontend

      - name: Run Prettier Check
        run: bun run format
        working-directory: ./frontend
